checkOverlap have standard method and sampling method
DUNE/dunendggd pull request #12
Opened 2022-12-08 21:27 UTC by krpalash

I included both method for checkOverlaps. we can't use both method simultaneously

2022-12-09 10:44 UTC, ast0815 commented
Can you please re-base your changes or merge the changes on master into your branch? Right now it is in conflict.
Also, please add your change to the `CHANGELOG.md`.

2023-01-13 11:00 UTC, ast0815 requested changes
Can you make the indentation consistent in your changes? I.e. replace the tabs with the right number of spaces?

2023-01-13 11:02 UTC, ast0815 commented
You write that both methods do not work at the same time. That is unfortunate. Instead of having to comment out the unused method, it would be much better to be able to choose the method with a command line flag. That way we can just run the same macro twice in the automated testing and do both checks.

Also, you still need to add your changes to the changelog.

2023-01-13 17:24 UTC, krpalash commented
how could I add changes to the changelog? what's the command for that?

2023-01-16 10:47 UTC, ast0815 commented
There is no command for it. You just need to add a line in the file `CHANGELOG.md`, describing what you changed. It is nothing special, just a text file to keep track of what changes in the software over time.

2023-01-17 15:48 UTC, krpalash commented
I commented on changelog. let me know ,please

2023-01-26 16:28 UTC, ast0815 commented
Hi @krpalash, it seems like you changed the indentation in the whole file, usually it is better to stick with the indentation convention already present. Otherwise it is more difficult to figure out what lines actually changed logically in the future. In this case it is almost a complete rewrite of the file anyway, so I guess it does not matter much.

The indentation seems inconsistent though. Some levels are 2 spaces and some are just one. Could you make it consistent please?

Also, please address the other changes I have requested before:

- Change the line in the CHANGELOG.md to adhere to the format of that file.
- Implement a check whether we are running in batch mode for both overlap checking methods, so they can both be used in the automated tests. See how it is done for the sampling method.

2023-01-26 18:11 UTC, krpalash commented
Regarding both method. I will try to implement. I already fixed indentation.

2023-01-27 09:21 UTC, ast0815 requested changes

2023-01-27 09:21 UTC, ast0815 commented on CHANGELOG.md
> +'checkOverlaps.C' now uses 1 to run sampling method. Other than 1 to run standard method.
```suggestion
- `checkOverlaps.C` now takes an optional argument to choose the overlap checking method. 
```

2023-01-27 09:21 UTC, ast0815 commented on CHANGELOG.md
> +##[checkOverlaps.c]
```suggestion

```

2023-01-27 09:21 UTC, ast0815 commented on CHANGELOG.md
> +-Standard method and sampling method have been integrated to overlaps of geometry.
```suggestion

```

2023-01-27 09:21 UTC, ast0815 commented on checkOverlaps.C
> +}
This curly bracket is at the wrong indentation. Also, your first indentation level is one space, while the second level is two spaces. Please make this consistent.

2023-02-02 12:21 UTC, merged