NDLAR Dead material change
DUNE/dunendggd pull request #13
Opened 2022-12-19 22:50 UTC by zhulcher

While doing an analysis looking at the effect of dead material in NDlar on reconstruction efficiencies, I noticed an approximately percent difference in the fraction of dead volume in NDlar between the CAD geometry which I have measurements from and the GDML, which I think might be relevant for my study. I believe i have made changes that fix it, but I would appreciate a second look! Specifically the gap dimensions and construction of the connection to the backplate don't currently match what I see in the CAD.

Thanks in advance,

Zach

2022-12-20 11:09 UTC, ast0815 commented
I don't know anything about the NDLAr geometry. Do you have a suggestion who should review the geometry changes?

2022-12-20 11:23 UTC, ast0815 requested changes

2022-12-20 11:23 UTC, ast0815 commented on .gitignore
> +*plotting.py
What is this `*plotting.py`? Should this really be ignored in the main repository? Same with the xml files. Are they a product of the workflow in the repository?

2022-12-20 11:23 UTC, ast0815 commented on duneggd/Config/ArgonCube/ArgonCubeDetector.cfg
> +N_Asic = 10
A lot of changes are just you removing spaces. Could you keep with the established config formatting (i.e. aligned equal signs) and only change the lines where you actually change something? Always better to keep things consistent. And you won't get git-blamed for lines where you did not actually change any parameters. ;)

Removing commented out configuration lines is totally fine though. Keeping comments of how things used to be before a change is a bit useless when we have the complete commit history.

2022-12-20 18:14 UTC, zhulcher commented
That should be a bit better now! I know Andrew Mastbaum edited part of the ND module geometry a while back? Otherwise, not the foggiest

2022-12-22 14:00 UTC, ast0815 commented on duneggd/ArgonCube/NDBucket.py
> +                ArgonColumn_lv.placements.append(FieldcageGap_pla.name)
Your editor seems to not add newlines at the end of files. Could you fix this as well?

2022-12-22 14:02 UTC, ast0815 commented
Looks much better. Could you add a line to the CHANGELOG.md about what you changed?

I will ask around who could do the review.

2023-01-17 14:03 UTC, ast0815 commented
Chris wrote me an e-mail, saying the changes look fine to him, and that he trusts you @zhulcher, that the changes are warranted.

Could you address the last few issues I flagged up, so we can merge this PR?

2023-01-24 13:55 UTC, ast0815 approved these changes

2023-01-24 13:55 UTC, merged