Re implement sand options history and update
DUNE/dunendggd pull request #15
Opened 2023-07-11 15:11 UTC by GianfrancoIngratta

The last merge eliminated the history of previous versions of the SAND geometry. Although the default version is unchanged from the last merge, here we want to restore the other options as well so that we can keep track of the evolution of the SAND geometry.

2023-07-12 04:06 UTC, ast0815 requested changes
Hi, this looks fine overall. But could you please remove the changes that introduce extra white spaces in empty lines, like line 148 in SAND_DRIFT.py?

2023-07-12 07:37 UTC, GianfrancoIngratta commented
not sure if you are referring to the right line number, but ok I think I got rid of some empty lines both in SAND_DRIFT.py and STT.py.
Moreover, I removed a config file "SAND_INNERVOLOPTDRIFT.cfg" that was previously renamed in  "SAND_INNERVOLOPTDRIFT1.cfg" and became useless.

2023-07-13 06:22 UTC, ast0815 commented on duneggd/SubDetector/SAND_DRIFT.py
> +
I mean lines like this. You removed an empty line, and added 4 spaces.

2023-07-13 06:24 UTC, ast0815 commented
You don't have to remove empty lines. Just don't add any whites paces in lines that were empty before.

2023-07-13 06:39 UTC, ast0815 commented
In general, it is good practice to avoid unrelated changes in white spaces like adding or removing empty lines or trailing white spaces (white spaces at the end of lines).

But actual edits of lines (where you change the code) should never introduce trailing white spaces, and remove them if they were there before. You can configure your `git diff` to highlight trailing white spaces for you.

2023-07-13 09:15 UTC, GianfrancoIngratta commented
I see your point now. 
In my new commit, I replaced the empty lines with some spaces introduced in the first commit with just empty lines. 
Hope this was the correct procedure to follow.

2023-07-17 12:26 UTC, ast0815 commented on duneggd/SubDetector/SAND_DRIFT.py
> +
This line still introduces trailing white spaces.

2023-07-19 09:38 UTC, ast0815 approved these changes
Now you have introduced lots of white space changes that have nothing to do with your actual code changes. This is not good practice, but good enough, since it only changes things for the better.

2023-07-19 09:38 UTC, merged