Build tms with updated geometry for PDR
DUNE/dunendggd pull request #33
Opened 2024-10-31 17:54 UTC by AsaNehm

2024-11-06 16:58 UTC, AsaNehm commented
Allows for the generation of two different types of geometries: pure stereo and full hybrid (every third layer an horizontal layer). To switch between them change in line 409 the variable to True for hybrid and False for stereo

2024-11-06 20:40 UTC, jdkio commented
Running small tests of 10 files of 1e15 pot each using [ProcessND.py](https://github.com/DUNE/ND_Production/wiki/Tutorial-for-ProcessND.py)
https://landscape.fnal.gov/lens/view/job/84036681.0@jobsub02.fnal.gov - stereo
https://landscape.fnal.gov/lens/view/job/58236578.0@jobsub03.fnal.gov - hybrid
If this works, I'd like to go up to 

Ideally, we'd make some plots to verify everything is adjusted the way we want. We've had geometry issues before, like where it was rotated 90 degrees. I've asked about plotting geometry efficiently on slack

It also sounds like we need to verify whether the reconstruction parameters may need adjustments. These test files could be used to validate that

2024-11-06 22:38 UTC, jdkio commented
Here are some jobs that worked. Only ran genie and g4 stages. Any failures were due to issues copying flux files
15101641.0@jobsub05.fnal.gov - stereo
58237315.0@jobsub03.fnal.gov - hybrid

Running tmsreco over 50 files from the output above. This version has a fix to the bar sanity check and I verfied it runs over at least one stereo output file above. But it seems to fail on most hybrid files, see below. It's tagged `kleykamp_2024-11-06_candidate` and branch `kleykamp_2024-11-06_tar_candidate`
84037506.0@jobsub02.fnal.gov - stereo
71686041.0@jobsub01.fnal.gov - hybrid

The hybrid file errors are very sparse. It just says,
```
Sliced event 111 into 2 slices
not in TMS?? hit 77(backwards) : 218.005, -1473.48, 11315
not in TMS?? hit 78(backwards) : 218.005, -1490.74, 11250
terminate called without an active exception
Aborted (core dumped)
```
Note that "not in TMS??" messages may or may not be related. There are additional "not in TMS??" messages that don't crash. The message comes from TMS_Kalman.  If there's no simple fix, we should make an issue to track this in dune-tms

The program doesn't crash at the same location if I turn off the kalman filter using the config file. But it still crashes with a seg fault:
`ConvertToTMSTree.exe /pnfs/dune/scratch/users/kleykamp/nd_production/2024-11-06_test_geom_v104_hybrid_small_edep_only/edep/FHC/00m/00/neutrino.29_1730927987.edep.root`
```
#6  0x00007f9f8d333eeb in TMS_TrackFinder::TrackMatching3D (this=this
entry=0x20a3b60 <TMS_TrackFinder::GetFinder()::Instance>) at /cvmfs/larsoft.opensciencegrid.org/products/gcc/v9_3_0/Linux64bit+3.10-2.17/i
nclude/c++/9.3.0/bits/std_abs.h:72
#7  0x00007f9f8d3405e3 in TMS_TrackFinder::FindTracks (this=this
entry=0x20a3b60 <TMS_TrackFinder::GetFinder()::Instance>, event=...) at TMS_Reco.cpp:523
#8  0x000000000040b326 in ConvertToTMSTree (filename=..., output_filename=...) at ../src/TMS_Reco.h:181
#9  0x0000000000408a86 in main (argc=<optimized out>, argv=<optimized out>) at ConvertToTMSTree.cpp:268
```

2024-11-07 08:45 UTC, ast0815 commented
> Ideally, we'd make some pictures of the geometry to verify everything is adjusted the way we want. We've had geometry issues before, like where it was rotated 90 degrees. I've asked about plotting geometry efficiently on slack

I tried and failed to implement that. The next best solution I could come up with was the 3D browser thing at https://dune.github.io/dunendggd/

It will always have the latest build geometry, so you can inspect the PR build there. Though it only builds the "default geometries" at the moment. So when you did not change those, you have to load your own geometry files from your PC into it. Which is no problem at all, just click on the three dots next to the file selector.

2024-11-07 15:27 UTC, jdkio commented
Thanks! I couldn't find the loading buttons. I had to adjust the center bar until the three dots became visible

2025-02-17 13:57 UTC, ast0815 requested changes
Looks good overall, but please see my comment about commented-out code.

Also, you have not recorded the changes in the CHANGELOG.md. Please do that.

2025-02-17 13:57 UTC, ast0815 commented on duneggd/Config/TMS.cfg
> +#thinbox2Dimension = [Q('3.498m'),Q('5.022m'),Q('0.015m')]
Please don't leave any commented-out lines of code in the source, unless they are there for a specific reason. And in that case, please specify that reason as part of the comment.

2025-02-17 14:01 UTC, ast0815 commented
Also, I just saw, that there is an inconsistency in the layer order when switching from the thin to the thicker layers:

![image](https://github.com/user-attachments/assets/31a74041-f05f-4d75-94b3-b8827eb043fa)

As you can see, there is goes XUVUX rather than XUVX (or whatever they are called now)

2025-02-17 14:03 UTC, AsaNehm commented on duneggd/Config/TMS.cfg
> +#thinbox2Dimension = [Q('3.498m'),Q('5.022m'),Q('0.015m')]
Will do. Thanks

2025-02-17 15:46 UTC, AsaNehm commented
> Also, I just saw, that there is an inconsistency in the layer order when switching from the thin to the thicker layers:
> 
> As you can see, there is goes XUVUX rather than XUVX (or whatever they are called now)

Thanks. I fixed this

2025-02-17 17:00 UTC, AsaNehm commented on duneggd/Config/TMS.cfg
> +#thinbox2Dimension = [Q('3.498m'),Q('5.022m'),Q('0.015m')]
Added comments for commented out lines. I'd like to keep them in for now to make it easier in case we have to revisit the old geometry for something (unlikely, but not impossible)

2025-02-17 17:19 UTC, AsaNehm commented
I updated the Changelog. Please let me know, if I need to change this further

2025-02-18 11:30 UTC, ast0815 requested changes

2025-02-18 11:30 UTC, ast0815 commented on CHANGELOG.md
> +
This should go under `[Unreleased]` with subsections named `Added`, `Changed`, `Removed`, etc, just like for the other releases. Don't give it your own heading.

2025-02-18 11:30 UTC, ast0815 commented on duneggd/Config/TMS.cfg
> +#thinbox2Dimension = [Q('3.498m'),Q('5.022m'),Q('0.015m')]
I don't see an explanation for this commented out line.

2025-02-18 11:30 UTC, ast0815 commented on duneggd/SubDetector/TMS.py
> +        """The commented out part here is a remnant from the old geometry with different steel widths (inner and outer)"""
Why write this as a string? Please describe the commented out block as part of the comment. E.g. just add `# Alternative geometry with only two steel thicknesses`. Don't call it "remnants". That does sound like something that should be just removed.
And then also mark which the actually executed blocks as `# Geometry with three steel widths` or something. So it is obvious which things need to be commented in or out when switching from one to the other.

2025-02-18 11:30 UTC, ast0815 commented on duneggd/SubDetector/TMS.py
> +        """Same here"""
"Same here" is not very descriptive. The comment should stand on its own. Also it would be better if the alternative geometries would be continuous blocks that can be commented in and out, rather than interleaving things. Makes it easier and less prone to mistakes when switching.

2025-02-18 11:30 UTC, ast0815 commented on duneggd/SubDetector/TMS.py
> +        """Same here"""
Same comment.

2025-02-18 11:30 UTC, ast0815 commented on duneggd/SubDetector/TMS.py
> +        """Same here"""
Same comment.

2025-02-18 11:30 UTC, ast0815 commented on duneggd/SubDetector/TMS.py
> +                                      dz = 0.5*Q("0.050m"))         # simply fill entire gap between steel
I don't understand the "Simply..." comments. What are the commented out values for?

2025-02-18 11:30 UTC, ast0815 commented on duneggd/SubDetector/TMS.py
> +                                    dz = 0.5*Q("0.017m"))# + Q("0.001m"))       # Same thickness as single bar
What are the commented out values for?

2025-02-18 11:35 UTC, AsaNehm commented on CHANGELOG.md
> +
Done now
Please explain somewhere in the document how to write this, if you expect other people to write this

2025-02-18 11:38 UTC, AsaNehm commented on duneggd/Config/TMS.cfg
> +#thinbox2Dimension = [Q('3.498m'),Q('5.022m'),Q('0.015m')]
Ah sry. Forgot to also do this in the config file. Taken care of now

2025-02-18 11:41 UTC, AsaNehm commented on duneggd/SubDetector/TMS.py
> +                                      dz = 0.5*Q("0.050m"))         # simply fill entire gap between steel
Same as before, the commented out values are from the 'older' geometry version. If we ever have to switch back, these are the values are the ones we need.

2025-02-18 11:41 UTC, AsaNehm commented on duneggd/SubDetector/TMS.py
> +                                    dz = 0.5*Q("0.017m"))# + Q("0.001m"))       # Same thickness as single bar
The commented out values are in case the aluminium case would be deployed. Can take them out

2025-02-18 11:45 UTC, ast0815 commented on duneggd/SubDetector/TMS.py
> +                                      dz = 0.5*Q("0.050m"))         # simply fill entire gap between steel
If possible, please make everything needed for one or the other geometry one block of code than can replace the other. At the very least, describe what those numbers are for in the comment. Or make these their own block of commented-out code with the proper description.

2025-02-18 11:46 UTC, ast0815 commented on duneggd/SubDetector/TMS.py
> +                                    dz = 0.5*Q("0.017m"))# + Q("0.001m"))       # Same thickness as single bar
Please take them out, or describe their function, or make a separate completely commented out code block where the numbers are actually used.

2025-02-18 11:46 UTC, AsaNehm commented on duneggd/SubDetector/TMS.py
> +        """The commented out part here is a remnant from the old geometry with different steel widths (inner and outer)"""
Changed the comment style and added a comment for the new geometry block as well.
I'm going to call it remnants, because it is highly unlikely, that the old geometry is ever needed again. If it bothers you that much, please change it yourself

2025-02-18 11:52 UTC, AsaNehm commented on duneggd/SubDetector/TMS.py
> +                                      dz = 0.5*Q("0.050m"))         # simply fill entire gap between steel
Added a comment on this in the lines above

2025-02-18 12:14 UTC, ast0815 requested changes
If you don't actually see the alternative geometry ever being used again, one could argue that it would be better just to remove those commented lines. Keeping track of things for posterity is handled by git, and it would be better not to clutter up the actual code. But fine, it looks good to me now. Just the changelog still is not in the format it should be in. You can just accept my suggested change to that one if you are happy with it.

2025-02-18 12:14 UTC, ast0815 commented on CHANGELOG.md
>  - Check for CHANGELOG update in PRs
```suggestion
### Changed

- TMS geometry update from CDR to PDR
  - Switch to 50 thin, 34 thick and 8 double thick steel planes with less material overburden in the y dimension
  - Change the dimension of scintillator bars, the amount of bars per module and the number of modules per layer
  - Introducing horizontal layer(X), currently in a vXuvXuv pattern with the first two layers being in front of the steel, while between the rest there is one layer of steel each in between
  - Increasing the air gap size
  - Double first layer of scintillator before the first layer of thin steel. There is also a layer of scintillator after the last layer of steel now

### Added

- Check for CHANGELOG update in PRs
```

2025-02-18 13:05 UTC, ast0815 approved these changes

2025-02-18 13:07 UTC, ast0815 commented
Thanks for incorporating my requests. Would you like to wait for @muether to review this as well, or should I merge?

2025-02-18 13:09 UTC, AsaNehm commented
I'll let you know after the TMS studies meeting today. Most likely waiting for @muether is not necessary

2025-02-18 14:59 UTC, merged